### ISSUE TITLE
https://anonymous.4open.science/r/ICL-D3IE-B1EE is expired

### ISSUE THREAD

**Issue by jpWang** [MAEHCM/ICL-D3IE#2]
Hi, thanks for your great work.
I want to ask that it seems like https://anonymous.4open.science/r/ICL-D3IE-B1EE is expired so it cannot be git clone. Can I just use this repo's (https://github.com/MAEHCM/ICL-D3IE) code? Are they the same?

Thanks!

**Comment by MAEHCM** [comment]
Yes, this is the updated repository for the paper. (https://github.com/MAEHCM/ICL-D3IE)
________________________________
发件人: Jiapeng Wang ***@***.***>
发送时间: 2023年12月13日 11:18
收件人: MAEHCM/ICL-D3IE ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MAEHCM/ICL-D3IE] https://anonymous.4open.science/r/ICL-D3IE-B1EE is expired (Issue #2)


Hi, thanks for your great work.
I want to ask that it seems like https://anonymous.4open.science/r/ICL-D3IE-B1EE is expired so it cannot be git clone. Can I just use this repo's (https://github.com/MAEHCM/ICL-D3IE) code? Are they the same?

Thanks!

―
