### ISSUE TITLE
Is the XYcut package self-written? Why didn't you find it?

### ISSUE THREAD

**Issue by reBiocoder** [MAEHCM/ICL-D3IE#3]
Is the XYcut package self-written? Why didn't you find it?

**Comment by MAEHCM** [comment]
No, it is under this branch https://github.com/MAEHCM/ICL-D3IE/blob/main/method/XYcut.py.

**Comment by MAEHCM** [comment]
No, it is under this branch: https://github.com/MAEHCM/ICL-D3IE/blob/main/method/XYcut.py.

**Comment by reBiocoder** [comment]
> No, it is under this branch: https://github.com/MAEHCM/ICL-D3IE/blob/main/method/XYcut.py.

Thanks!
